// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6tv2DPi-w14PHOMh4dRp4HF6Rz7eFnc',
    appId: '1:109376900105:web:625379f7e15b769dbf7cd8',
    messagingSenderId: '109376900105',
    projectId: 'serenique-f58ce',
    authDomain: 'serenique-f58ce.firebaseapp.com',
    storageBucket: 'serenique-f58ce.firebasestorage.app',
    measurementId: 'G-TCSGP494FB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD04V85n_ex7fLFUsGtM5RkrFNxNTLZU40',
    appId: '1:109376900105:ios:9c868c0541840b4bbf7cd8',
    messagingSenderId: '109376900105',
    projectId: 'serenique-f58ce',
    storageBucket: 'serenique-f58ce.firebasestorage.app',
    iosBundleId: 'com.example.sereniqueFreshStart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe6tv2DPi-w14PHOMh4dRp4HF6Rz7eFnc',
    appId: '1:109376900105:web:2ace532eddc0a309bf7cd8',
    messagingSenderId: '109376900105',
    projectId: 'serenique-f58ce',
    authDomain: 'serenique-f58ce.firebaseapp.com',
    storageBucket: 'serenique-f58ce.firebasestorage.app',
    measurementId: 'G-0JZCXB9LH7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD04V85n_ex7fLFUsGtM5RkrFNxNTLZU40',
    appId: '1:109376900105:ios:9c868c0541840b4bbf7cd8',
    messagingSenderId: '109376900105',
    projectId: 'serenique-f58ce',
    storageBucket: 'serenique-f58ce.firebasestorage.app',
    iosBundleId: 'com.example.sereniqueFreshStart',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0qzU9QHgeHL7NscE8-752d9ANSAFvgJs',
    appId: '1:109376900105:android:9f79cab6d7d5e2e4bf7cd8',
    messagingSenderId: '109376900105',
    projectId: 'serenique-f58ce',
    storageBucket: 'serenique-f58ce.firebasestorage.app',
  );

}