// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example: this file will be generated when you run `flutterfire configure`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwiWgKcRhsFGvvn4IGxUBs7VFcJwTgTzw',
    appId: '1:2957169306:web:your-web-app-id', // You'll need to get this from Firebase Console
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    authDomain: 'serenique-avni.firebaseapp.com',
    storageBucket: 'serenique-avni.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwiWgKcRhsFGvvn4IGxUBs7VFcJwTgTzw',
    appId: '1:2957169306:android:your-android-app-id', // You'll need to get this from Firebase Console
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    storageBucket: 'serenique-avni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwiWgKcRhsFGvvn4IGxUBs7VFcJwTgTzw',
    appId: '1:2957169306:ios:your-ios-app-id', // You'll need to get this from Firebase Console
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    storageBucket: 'serenique-avni.appspot.com',
    iosBundleId: 'com.example.serenique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwiWgKcRhsFGvvn4IGxUBs7VFcJwTgTzw',
    appId: '1:2957169306:ios:your-macos-app-id', // You'll need to get this from Firebase Console
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    storageBucket: 'serenique-avni.appspot.com',
    iosBundleId: 'com.example.serenique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwiWgKcRhsFGvvn4IGxUBs7VFcJwTgTzw',
    appId: '1:2957169306:web:your-windows-app-id', // You'll need to get this from Firebase Console
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    authDomain: 'serenique-avni.firebaseapp.com',
    storageBucket: 'serenique-avni.appspot.com',
  );
}
