// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example: this file will be generated when you run `flutterfire configure`
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwiWgKcRhsFGvvn4IGxUBs7VFcJwTgTzw',
    appId: '1:2957169306:web:87da992e2115a7cb6a0523',
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    authDomain: 'serenique-avni.firebaseapp.com',
    storageBucket: 'serenique-avni.firebasestorage.app',
    measurementId: 'G-13TV3PG6ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDchZu7tmPPuzuXp5pCM8_q9Ho_Mvs9qx8',
    appId: '1:2957169306:android:3f434ecf146b93c96a0523',
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    storageBucket: 'serenique-avni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pXcuJo8aHkkxuhxCezgDRVHzIHcIJOo',
    appId: '1:2957169306:ios:994466c04363f5376a0523',
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    storageBucket: 'serenique-avni.firebasestorage.app',
    iosBundleId: 'com.example.serenique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3pXcuJo8aHkkxuhxCezgDRVHzIHcIJOo',
    appId: '1:2957169306:ios:994466c04363f5376a0523',
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    storageBucket: 'serenique-avni.firebasestorage.app',
    iosBundleId: 'com.example.serenique',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwiWgKcRhsFGvvn4IGxUBs7VFcJwTgTzw',
    appId: '1:2957169306:web:6e34e3cf84e47c396a0523',
    messagingSenderId: '2957169306',
    projectId: 'serenique-avni',
    authDomain: 'serenique-avni.firebaseapp.com',
    storageBucket: 'serenique-avni.firebasestorage.app',
    measurementId: 'G-4HM63ZCJ0K',
  );
}
